### ISSUE TITLE
Modify `throttle` import to eliminate deprecation warning

### ISSUE THREAD

**Issue by jacobq** [heroku/ember-sortable#161]
When using this addon in an Ember v2.16.2 app I encounter the deprecation notice shown below. 
This appears to be caused by 
[`import { throttle } from 'ember-runloop';`](https://github.com/jgwhite/ember-sortable/blob/91cccd91b69b42ac78570ae75008a559ca4f3edc/addon/mixins/sortable-item.js#L6).

Is there a simple way to update this without breaking older 2.x versions?

```
DEPRECATION: Importing from the `ember-runloop` module has been deprecated. Please use the new module imports:

import { run } from '@ember/runloop'
import { begin } from '@ember/runloop'
import { bind } from '@ember/runloop'
import { cancel } from '@ember/runloop'
import { debounce } from '@ember/runloop'
import { end } from '@ember/runloop'
import { join } from '@ember/runloop'
import { later } from '@ember/runloop'
import { next } from '@ember/runloop'
import { once } from '@ember/runloop'
import { schedule } from '@ember/runloop'
import { scheduleOnce } from '@ember/runloop'
import { throttle } from '@ember/runloop'

 [deprecation id: ember-cli-shims.deprecated-shims] See https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md for more details.
        at logDeprecationStackTrace (serve://dist/assets/vendor.js:29291:21)
        at HANDLERS.(anonymous function) (serve://dist/assets/vendor.js:29513:9)
        at raiseOnDeprecation (serve://dist/assets/vendor.js:29321:14)
        at HANDLERS.(anonymous function) (serve://dist/assets/vendor.js:29513:9)
        at invoke (serve://dist/assets/vendor.js:29525:9)
        at Object.deprecate (serve://dist/assets/vendor.js:29379:24)
        at Module.callback (serve://dist/assets/vendor.js:89140:15)
        at Module.exports (serve://dist/assets/vendor.js:111:32)
        at Module._reify (serve://dist/assets/vendor.js:148:59)
logDeprecationStackTrace @ deprecate.js:115
HANDLERS.(anonymous function) @ handlers.js:14
raiseOnDeprecation @ deprecate.js:127
HANDLERS.(anonymous function) @ handlers.js:14
invoke @ handlers.js:26
deprecate @ deprecate.js:185
(anonymous) @ app-shims.js:267
Module.exports @ loader.js:106
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
requireModule @ loader.js:27
win.require.args @ (index):166
_extractDefaultExport @ index.js:392
resolveOther @ index.js:113
superWrapper @ ember-utils.js:437
resolve @ resolver.js:144
resolve @ container.js:852
resolve @ container.js:542
resolve @ container.js:546
factoryFor @ container.js:95
factoryFor @ container_proxy.js:40
componentFor @ component_lookup.js:9
componentFor @ component-lookup-mixin.js:9
superWrapper @ ember-utils.js:437
lookupComponentPair @ lookup-component.js:41
lookupComponent @ lookup-component.js:66
Environment._this._definitionCache._emberMetal.Cache.name @ environment.js:34
get @ ember-metal.js:2439
getComponentDefinition @ environment.js:144
refineBlockSyntax @ syntax.js:36
compile @ runtime.js:4413
(anonymous) @ runtime.js:4067
compile @ runtime.js:3958
compileStatement @ runtime.js:4716
compileStatements @ runtime.js:4721
compileStatic @ runtime.js:4746
(anonymous) @ runtime.js:845
evaluate @ runtime.js:70
next @ runtime.js:7246
execute @ runtime.js:7232
insert @ runtime.js:6682
nextInsert @ reference.js:694
nextAppend @ reference.js:657
sync @ reference.js:617
evaluate @ runtime.js:6765
execute @ runtime.js:6497
rerender @ runtime.js:6855
_this.render @ renderer.js:69
exports.runInTransaction @ ember-metal.js:652
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_revalidate @ renderer.js:418
invoke @ backburner.js:274
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4393
(anonymous) @ has_element.js:18
exports.flaggedInstrument @ ember-metal.js:3787
handleEvent @ has_element.js:17
exports.default._emberMetal.Mixin.create._Mixin$create.handleEvent @ view_support.js:177
_bubbleEvent @ event_dispatcher.js:277
(anonymous) @ event_dispatcher.js:211
dispatch @ jquery.js:5201
elemData.handle @ jquery.js:5009
```

**Comment by jgwhite** [comment]
Thanks for reporting. We’ll ship a release that is fully ember 2.16.x compatible soon 🙂

**Comment by BnitoBzh** [comment]
If you want any help to do this ...

**Comment by jgwhite** [comment]
This seems to have been fixed upstream by ember/ember-cli. Please re-open if it’s still an issue.
